project.yaml
schema.graphql
src/mappings/mappingHandlers.ts

Addressing #8: 
- Implements JSON `coin` type within the schema
- Introduces a new handler `handleNativeTransfer`
- Includes schema updates for the `NativeTransferMsg` type and the `NativeTransfer` db entity

feat: native transfer handler

---

Pipfile
test/base.py

Tests:e2e setup

---

.github/workflows/docker_deploy_prod.yml

See: https://github.com/fetchai/ledger-subquery/runs/7917890428?check_suite_focus=true for an example failure.
Fixes broken github action, [docker_deploy_prod.yml](https://github.com/fetchai/ledger-subquery/blob/main/.github/workflows/docker_deploy_prod.yml).

fix: docker deploy prod action

---

schema.graphql
src/mappings/mappingHandlers.ts
test/helpers/field_enums.py
test/test_native_primitives.py

- adds `signerAddress` field to the transaction entity

feat: add signerAddress field to tx

---

docker-compose.yml
docker/fetchd.dockerfile
scripts/00_setup_fetchd_local.sh
scripts/fetchd-entrypoint.sh

Adds a fetchd node to the docker composition for use with end-to-end tests.

chore: add fetchd node to docker-compose.yml

---

schema.graphql
src/mappings/mappingHandlers.ts
test/test_legacy_bridge_swap.py

- adds `executeContractMessage` field to `LegacyBridgeSwap` entity
- misc. simplifications, renames, etc.

chore: add executeContractMessage field to LegacyBridgeSwap entity

---

project.yaml
schema.graphql
src/mappings/mappingHandlers.ts
src/mappings/utils.ts
test/helpers/field_enums.py
test/test_delegation_reward_claim.py

- add `amount` and `denom` fields to `DistDelegatorClaim`
- populate amount/denom with correlated "withdraw_reward" event
- reduce gql test query logic
- test IDs of related entities

chore: add DistDelegatorClaim amount & denom

---

README.md
package.json

- bump package.json version to v0.1.0
- update package.json name and description
- update README.md

chore: bump version & update README

---

k8s/subquery/values.yaml

Increased disk size to 30Gi
Issue: https://github.com/fetchai/ledger-subquery/issues/77

Increase disk size to 30Gi

---

docs/assets/architecture.puml
docs/assets/architecture.svg
docs/assets/architecture_legend.puml
docs/assets/architecture_legend.svg
docs/assets/entities.puml
docs/assets/entities.svg
docs/assets/entities_legend.puml
docs/assets/entities_legend.svg
docs/introduction.md
mkdocs.yml

- adds mkdocs.yml for integration with fetchai/docs
- adds an architecture component diagram
- adds an entity relationship diagram for primitive entities
- adds an introduction document explaining the basics of ledger-subquery
- links to external docs
---

docs: add introduction

---

docs/introduction.md

- adds endpoints table with network name and API / playground URL

docs: add endpoints to introduction

---

.eslintrc.yml
.github/workflows/test.yml
package.json
src/index.ts
src/mappings/bank/balanceChange.ts
src/mappings/bank/index.ts
src/mappings/bank/transfer.ts
src/mappings/dist/rewards.ts
src/mappings/gov/index.ts
src/mappings/gov/votes.ts
src/mappings/ibc/index.ts
src/mappings/ibc/transfer.ts
src/mappings/primitives.ts
src/mappings/wasm/bridge.ts
src/mappings/wasm/contracts.ts
src/mappings/wasm/cw20.ts
yarn.lock

- adds [ESlint](https://eslint.org/) 
- runs TypeScript linter in CI
- #137

chore: add ESlint

---

docs/introduction.md

| **Before** | **After** |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/600733/195841511-f6f50585-7b81-4642-bfe5-78b36f1588be.png) | ![image](https://user-images.githubusercontent.com/600733/195841419-7960f70b-8925-4a83-b467-97c3eaf81458.png) |

docs: fix tip usage

---

.github/workflows/test.yml
jest.config.js
tests/unit/contracts/jaccard.test.ts

- adds TypeScript unit tests to CI
- moves tests/ts/jaccard.test.ts to tests/unit/contract/jaccard.test.ts
- sets Jest root directory to prevent execution of subql packages' tests :grimacing:

test: Jest

---

tests/e2e/entities/test_authz_exec.py
tests/helpers/field_enums.py

- reduces `NamedFields` descendants to no longer need to define `select_query` and/or `select_where`
- fixes authz test assertion

test: fix authz test and refactor named fields

---

.gmrc
docker-compose.yml
docker/plv8.dockerfile
migrations/current.sql
package.json
yarn.lock

**Addressing #91**
- includes `graphile-migrate` dependency

chore: add initial graphile-migrate setup

---

src/genesis/helpers/__init__.py
src/genesis/helpers/field_enums.py
src/genesis/observers/balances.py
tests/e2e/entities/test_CW20_balance_change.py
tests/e2e/entities/test_CW20_transfer.py
tests/e2e/entities/test_authz_exec.py
tests/e2e/entities/test_contract_deploy.py
tests/e2e/entities/test_delegation_reward_claim.py
tests/e2e/entities/test_execute_contract_message.py
tests/e2e/entities/test_gov_proposal_vote.py
tests/e2e/entities/test_legacy_bridge_swap.py
tests/e2e/entities/test_native_balances.py
tests/e2e/entities/test_native_primitives.py
tests/e2e/entities/test_native_transfer.py
tests/e2e/observers/test_accounts.py
tests/e2e/observers/test_balances.py
tests/helpers/__init__.py

Moved tests/helpers/field_enums.py to src/genesis/helpers/field_enums.py

Promoted field_enums to library

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/pull_request_template.md
CODE_OF_CONDUCT.md

- add bug report issue template
- add feature request issue template
- add code of conduct (referenced in issue templates)
- add pull request template _(out of original issue scope but low level of effort)_
---

docs: issue & pull request templates

---

.github/pull_request_template.md

I've found the checklist extremely useful even in the very short time it's been employed. I've observed that DB migrations are needed to accompany PRs more often than not , and as such it seems like an easy thing to forget, especially when we're in a rush.
Add 2 checklist items regarding DB migrations to ensure their existence and correctness, when applicable.
---

chore: update PR template re: DB migrations

---

k8s/subquery/conf/healthcheck.sh
k8s/subquery/templates/health/configmap.yaml
k8s/subquery/templates/health/cronjob.yaml
k8s/subquery/values.yaml

Added cronjob to monitor subquery environments every 5 minutes and send push notification if not working
---

Added basic statuscake alerts

---

schema.graphql

https://github.com/fetchai/ledger-subquery/pull/211#discussion_r1044270565
- removes redundant index decorator on Cw20BalanceChange entity
---

chore: remove redundant index decorator

---

README.md

The command to run all e2e tests has gone out of date. I've also noticed that I tend to run specific tests, locally, more often than I run all tests.
- fix command to run all e2e tests
- add command to run specific test module
---

docs: readme: expand on how to use e2e tests

---

migrations/committed/000005.sql
migrations/committed/000006.sql
schema.graphql
src/genesis/helpers/field_enums.py
src/mappings/wasm/contracts.ts
tests/e2e/entities/test_delegation_reward_claim.py
tests/e2e/entities/test_execute_contract_message.py
tests/e2e/entities/test_gov_proposal_vote.py

- Changes to the schema to amend the `contract` field of the `execute_contract_message` entity. 
- This field now holds a reference to the related contract, creating a new relation.
- Revision of the end-to-end tests to reflect this schema change.
**Addressing** #200 
---

feat: add contract to execute msg

---

Pipfile
Pipfile.lock
tests/e2e/entities/test_CW20_balance_change.py
tests/e2e/entities/test_CW20_transfer.py
tests/e2e/entities/test_contract_deploy.py
tests/e2e/entities/test_execute_contract_message.py
tests/e2e/entities/test_legacy_bridge_swap.py
tests/helpers/contracts.py

- Introduces a concrete CosmPy version in the `Pipfile`
- Updated contract deployment helpers for end-to-end testing, as this CosmPy version introduces a breaking change to the deployment of contracts
- Matching changes to the test suite
**Addressing:** #218
---

chore: set concrete cosmpy version

---

README.md

- remove redundant `yarn install` instruction
---

docs: readme tweak

---

setup.cfg

Added ignore E203 to setup.cfg
---

lint: Added ignoring of E203

---

docs/introduction.md

While referencing documentation, I noticed this was missing.
- adds event attributes to primitive entities list
---

docs: add event attributes to primitive entities

---

.gitmodules
Pipfile
Pipfile.lock
tests/e2e/entities/test_almanac.py
tests/helpers/identity.py

refactor: Removed uagents as submodule

---

src/genesis/helpers/field_enums.py
src/genesis/observers/__init__.py
src/genesis/observers/balances.py
tests/e2e/entities/test_CW20_balance_change.py
tests/e2e/entities/test_CW20_transfer.py
tests/e2e/entities/test_authz_exec.py
tests/e2e/entities/test_contract_deploy.py
tests/e2e/entities/test_delegation_reward_claim.py
tests/e2e/entities/test_execute_contract_message.py
tests/e2e/entities/test_gov_proposal_vote.py
tests/e2e/entities/test_legacy_bridge_swap.py
tests/e2e/entities/test_native_balances.py
tests/e2e/entities/test_native_primitives.py
tests/e2e/entities/test_native_transfer.py
tests/e2e/observers/test_balances.py

1. Some inconsistencies have developed over time around the convention
2. The recent python linting PRs and resulting refactoring has illustrated the cost of unnecessary complexity in this area of the code
- rename python model classes to match their respective table names
- table name is the lower snake case of the respective class name
- clean up any inconsistencies
- compute table name in parent class using sub-class name
- remove (now redundant) `get_table` methods from `NamedFields` sub-classes
---

refactor: python models

---

.github/workflows/docker_deploy_prod.yml

added pipeline steps to build and push postgres docker image

added pipeline steps to build and push postgres docker image

---

docker/node.dockerfile

Include dependency requirements for production workflow to build `subquery-node`.
---

fix: add node requirements for prod workflow build
