fetchai/ledger-subquery

project.yaml

- Uncomment `chainTypes` in the project.yaml to prevent the following error:
```
failed to index block at height 5585256 handleMessage([{"idx":0,"tx":{"idx":0,"block":{"block":{"id":"E105D0370D8C594E73CC23BDE0E43422512643B07709F9C40275B05923F8767F","header":{"version":{"block":"11","app":"0"},"height":5585256,"chainId":"fetchhub-4","time":"2022-04-25T15:15:38.385747527Z"},"txs":[{"0":10,"1":93,"2":10,"3":91,"4":10,"5":34,"6":47,"7":99,"8":111,"9":115,"10":109,"11":111,"12":115,"13":46,"14":115,"15":108,"16":97,"17":115,"18":104,"19":105,"20":110,"21":103,"22":46,"23":118,"24":49,"25":98,"26":101,"27":116,"28":97,"29":49,"30":46,"31":77,"32":115,"33":103,"34":85,"35":110,"36":106,"37":97,"38... Error: Unregistered type url: /cosmos.slashing.v1beta1.MsgUnjail at Registry.lookupTypeWithError …
```

fix: uncomment chainTypes

---

project.yaml
schema.graphql
src/mappings/mappingHandlers.ts
src/mappings/types/common.ts
src/mappings/types/index.ts
src/mappings/types/messages.ts

- add [fetch subquery dictionary](https://explorer.subquery.network/subquery/subquery/cosmos-fetch-ai-dictionary) to project.yaml
- schema improvements
- related entities are connected by an edge with the direction going from the more specific entity to the more general entity, in a one-to-one relationship; or from the many-side to the one-side, in a  or many-to-one relationship (i.e. the more specific entity / many-side holds the foreign key)
- fix ExecuteEvent type name typo
- add indexes
- add reverse relationship lookups
- de-duplicate fields
- specify the https port for the network endpoint (just in case :sunglasses:)
- register handler for all messages, events, transactions and blocks
- collecting all available information such that more specific object types (e.g. …

chore: improve forward compatibility

---

.github/workflows/docker_build.yml
.github/workflows/docker_deploy_prod.yml

_Based on workflows from [fund-backend](https://github.com/fetchai/fund-backend)_
- Add docker_build workflow: Builds and pushes the `subquery-node` image on update or opening of a PR to the `main` branch. Image tag is `latest`.
- Add docker_deploy_prod: Builds and pushes the `subquery-node` image on merge to the `main` branch. Image tag is the truncated hash of the git commit from which it was build.

chore: add actions to build and push docker images

---

k8s/subquery/values.yaml

Increases the default helm value for the size of the persistent volume from 1[Gi](https://simple.wikipedia.org/wiki/Gibibyte) to 7Gi. This default value only applies when using the helm cli, (e.g. `helm install <chart instance name> ./k8s/subquery/ -f ./k8s/subquery/values.yaml -n subquery`). This is only the case while experimenting in the sandbox.
fetchai/ecosystem-tasks#114

chore: subquery db storage size default value

---

.dockerignore
docker/api.dockerfile
docker/node.dockerfile
scripts/build-docker.sh

Paths were incorrectly (automatically) updated when moving Dockerfile to ./docker/node.dockerfile (in #42). :sweat_smile: 
I do not recall experiencing any issue when using docker compose (despite having likely rebuilt at some point). The issue presented when attempting to build with build-docker.sh.
- update `COPY`/`ADD`/`ARG` paths in dockerfiles to be relative to docker context
- update build-docker.sh to support multiple dockerfiles and git root dirs (latter, for image tag only)
- add .data/ (local postgres data) directory to .dockerignore

fix: dockerfile paths

---

Pipfile
Pipfile.lock
test/base.py
test/helpers/field_enums.py
test/test_native_primitives.py

- add end-to-end test coverage for initial native entities:
- Block
- Transaction
- Message
- Event
- adds `psycopg` to the Pipfile and updates Pipfile.lock
- refactors common config values to constants
https://github.com/fetchai/ecosystem-tasks/issues/43

tests: e2e native primitive coverage

---

schema.graphql
src/mappings/mappingHandlers.ts

_(Extracted from #28)_
- changes block timestamp data type from `String` to `Date`

chore: change block timestamp to Date type

---

src/mappings/mappingHandlers.ts

- applies `JSON.stringify` to event attribute values

fix: serialize binary event attribute values with JSON

---

test/base.py
test/helpers/field_enums.py
test/test_delegation_reward_claim.py
test/test_execute_contract_message.py
test/test_gov_proposal_vote.py
test/test_legacy_bridge_swap.py
test/test_native_primitives.py
test/test_native_transfer.py

- refactors all DB cleanup code to `Base.clean_db`
- move applicable test setup code to `setUpClass` methods to reduce run-time
- add enum classes to represent DB tables' columns for clearer data access semantics with psycopg3
- rename some variables for clarity
- add spacing around operators
- tidy up imports

test: tidying up e2e tests

---

project.yaml

Error:
```
ERROR Failed to decode message Error: Unregistered type url: /cosmos.slashing.v1beta1.MsgUnjail
2022-08-29T05:03:27.875Z <fetch> ERROR failed to index block at height 2590346 handleMessage() Error: Unregistered type url: /cosmos.slashing.v1beta1.MsgUnjail
```
Solution:
- move chainTypes to `network` section instead of `dataSources`
https://github.com/subquery/cosmos-subql-dictionaries/blob/main/project_fetchhub.yaml#L17

fix: added chainTypes in network

---

.github/workflows/docker_deploy_prod.yml

- Updated GitHub action to use `api.dockerfile` to build graphql API dockerimage

fix: api docker build github action

---

scripts/node-entrypoint.sh

Issue: https://github.com/fetchai/ledger-subquery/issues/60
Details:
- Support to override legacy bridge contract address in `project.yaml`
- It can be overridden with an environment variable: `LEGACY_BRIDGE_CONTRACT_ADDRESS`
- The existing `node-entrypoint.sh` has been updated to override the contract address if the environment variable is provided variables.

chore: added support to update bridge contract address

---

docker-compose.yml
project.yaml

- remove postgres data volume from docker-compose by default 
- improves TDD workflow
- can be added via docker-compose.override.yml
-  add `LEGACY_BRIDGE_CONTRACT_ADDRESS` in docker-compose to match contract with code 0
- update legacy bridge contract address in project.yaml to the testnet bridge (fetch-side) contract address
- docker-compose.yml defaults to testnet config

fix: devops bits

---

schema.graphql
src/mappings/mappingHandlers.ts
src/mappings/types/messages.ts
test/helpers/graphql.py
test/test_native_transfer.py

- replace gql schema type with vanilla TypeScript type (not necessary to be a gql schema type)
- refactor native transfer gql queries
- add message field to the native transfer entity

chore: add message field to native transfer entity

---

src/mappings/utils.ts

- fixes an error:
```
2022-09-01T13:16:35.435Z <fetch> INFO fetch block [839146,839245], total 100 blocks
2022-09-01T13:16:35.523Z <fetch> ERROR failed to index block at height 839046 handleDelegatorWithdrawRewardEvent() Error: Input exceeds uint64 range
```

fix: parseCoins

---

docker-compose.yml
project.yaml
schema.graphql
src/mappings/mappingHandlers.ts
test/base_contract.py
test/helpers/field_enums.py
test/test_execute_contract_message.py
test/test_legacy_bridge_swap.py

- Remove the hardcoded address on the handleLegacyBridgeSwap, as this address is dependant on the number of previously stored / instantiated contracts
- Instead extract the contract address from the swap tx, which should still allow querying all swaps for a particular contract
- rename `BaseContract` to `BridgeContract`, in anticipation of supporting other kinds of contracts (ie: CW20)
- reduced sleep time in `TestContractSwap` to wait only for indexer to pickup the messages, it now wait for the swap tx using cosmpy `wait_for_query_tx()`

fix: bridge contract remove hardcoded address

---

scripts/node-entrypoint.sh

As of #70, we're generalizing contract instances, subsequently, this part of the project.yaml modification is no longer necessary.

fix: remove LEGACY_BRIDGE_CONTRACT_ADDRESS from node-entrypoint.sh

---

.dockerignore
.github/workflows/test.yml
ci-compose.yml
docker/fetchd.dockerfile

- use pre-built fetchd base-image (faster)
- use CI-specific docker compose file
- ensure all node_modules directories are covered by dockerignore file
- add workflow to exercise end-to-end tests

chore: run e2e tests in CI

---

docker-compose.yml
project.yaml
schema.graphql
src/mappings/mappingHandlers.ts
test/helpers/field_enums.py
test/helpers/regexes.py
test/test_native_balances.py

From a rebased #54, reworked `handleNativeBalanceDecrement` and `handleNativeBalanceIncrement` to index individual `coin_received` and `coin_spent` events, allowing to query for all the "balance changed" events for a particular account, and a 3rd party to compute the total balance at any point. 
This approach mainly allows the creation of some external script parsing the genesis file and inserting `NativeBalance` rows for accounts with their initial balances.
It also avoids maintaining some "total" balance number as this could quickly become inconsistent on any indexer failures without a way to know it. The main idea is to keep the door open for any "reindexing" or "replaying" options in case of anythings going wrong.
This PR still needs a bunch of tests to be added on the graphql side of …

feat: account balance tracking

---

src/genesis/observers/__init__.py

Fixes the delay argument that is passed to `BalanceObserver#observe`. The method signature was recently changed and my IDE was too borked to notice the type hint violation.

fix: delay argument

---

schema.graphql
src/genesis/observers/balances.py

- renames `NativeBalance` entity (`native_balances` table) to `GenesisBalance` (`genesis_balances`) for clarity
- rename `Account#nativeBalances` field to `Account#genesisBalances`

chore: rename NativeBalance table to GenesisBalance

---

src/mappings/mappingHandlers.ts

Replace destructuring assignment with regular variable assignment using the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to simplify checking for undefined values.

fix: swaps handler undefined checking

---

scripts/node-entrypoint.sh

- forward script arguments to SubQuery CLI
_Previously, any command arguments were actually being ignored (e.g. [docker-compose:39](https://github.com/fetchai/ledger-subquery/blob/main/docker-compose.yml#L39), [node.sts.yml:27](https://github.com/fetchai/ledger-subquery/blob/main/k8s/subquery/templates/name/node.sts.yml#L27))._

fix: forward script arguments to subquery CLI

---

package.json

Adds `yarn lint:fix` to fix simple TypeScript linting errors.

chore: add lint:fix yarn script to fix linter simple errors

---

src/mappings/wasm/contracts.ts

- improve formatting of `saveContractEvent` warning
- use `JSON.stringify` to prevent logging the string literal `[object Object]`
- add line breaks to ease readability (log output is multiple lines)

chore: improve warning formatting in saveContractEvent helper

---

.gmrc
README.md
migrations/committed/000001.sql
migrations/current.ts
migrations/initial_schema/000001.sql
migrations/src/000001.ts
package.json

- add [.gmrc]() action to run migrations/initial_schema.sql on reset (`graphile-migrate reset --erase`)
- add placeholder files for facilitating migrations workflow:
- migrations/current.ts
- migrations/current.sql
- migrations/initial_schema.sql
- add package script to build migration TypeScript with plv8ify
- retroactively add migration for #82 
- add DB migrations section to the readme

chore: authz support DB migration

---

migrations/committed/000005.sql
schema.graphql
src/genesis/helpers/field_enums.py
src/mappings/wasm/bridge.ts
tests/e2e/entities/test_execute_contract_message.py
tests/e2e/entities/test_legacy_bridge_swap.py
tests/helpers/contracts.py

- **Wait for #210 to be merged** 
- Migration order needs to be updated, as that PR also features migration number 5. 
- Amends `legacy_bridge_swap` entity to include relation to relevant `contract` entity.
- changes `contract` field to include this relation, instead of storing contract address only.
- Refactors bridge contract deployment to allow for multiple instances, for test repeatability.
**Addressing** #200

feat: add contract relation to legacy bridge swap

---

tests/e2e/entities/test_CW20_balance_change.py
tests/e2e/entities/test_CW20_transfer.py
tests/e2e/entities/test_contract_deploy.py
tests/e2e/entities/test_delegation_reward_claim.py
tests/e2e/entities/test_execute_contract_message.py
tests/e2e/entities/test_gov_proposal_vote.py
tests/e2e/entities/test_legacy_bridge_swap.py
tests/e2e/entities/test_native_balances.py
tests/e2e/entities/test_native_primitives.py
tests/e2e/entities/test_native_transfer.py
tests/helpers/graphql.py

- Changes `test_filtered_query` to `filtered_test_query`
- Breaks `UnitTest` association, avoiding unnecessary failing tests.
**Addressing:** #212

fix: rename filter query

---

package.json

I've noticed some warnings recently about this duplicate.
- remove duplicate package script (`start:docker`)
---

fix: package.json remove duplicate script

---

tests/helpers/clients.py

Recently, I presume due to a pipfile update or something, the logger contained in the graphql client package we're using in our end-to-end tests has become unusably verbose by default; see [gql docs -> logging -> disabling logs](https://gql.readthedocs.io/en/latest/advanced/logging.html#disabling-logs).
- Set log level to WARNING insetad of INFO for gql client / aiohttp transport
See #187 CI output:
- [Before](https://github.com/fetchai/ledger-subquery/actions/runs/3686304284/jobs/6238350465) - (fd1f8f7)
- [After](https://github.com/fetchai/ledger-subquery/actions/runs/3695154429/jobs/6257190485) - (af85236)
---

fix: set WARNING level on gql aiohttp transport logger

---

project.yaml

Implements the `includeFailedTx` flag in the project manifest file
- Allows failed transactions to be indexed
---

fix: allow indexing of failed transactions
